name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
      - "releases/*"

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Cache Qodana
        uses: actions/cache@v3
        with:
          path: ~/.cache/JetBrains/qodana
          key: qodana-${{ runner.os }}-${{ hashFiles('**/package*.json', '**/yarn.lock') }}
          restore-keys: |
            qodana-${{ runner.os }}-

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          args: --fail-threshold 0
          upload-result: true
          pr-mode: ${{ github.event_name == 'pull_request' }}
          post-pr-comment: ${{ github.event_name == 'pull_request' }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
